### PR TITLE
Quiz mid-v1.3

### LINKED ISSUE #104: fix answer input to allow 0 or more characters
Currently, even for `PREVIEW` type of question, the user still needs to type something before he can move on to the next question. Also, it must be 2 characters or more, else it will be detected as invalid input.

So it needs to be changed such that a blank answer is accepted as an answer.

### LINKED ISSUE #105: [QUIZ] Include message to say that it is what it is
Preview: needs to be explicit it is in the preview mode
Correct answer: be more obvious it is the correct answer
Wrong answer: input answer should be shown so that the user knows what he typed

### PR DESCRIPTION
**Pull request by halcyoneee**
**New**:
- Adds new quiz command to label question as difficult (but not yet fully implemented, not saved outside of quiz)

**Update**:
- Allows 0 or more character as answer, previously 2 or more (closes #104)
- Updates feedback message given to user during quiz (closes #105)
- Changes to UI such that there is a difference between management and quiz mode 
- Moves `QuizModel` and `QuizModelManager` up a package to simplify project structure
- Moves the rest of `quiz` subpackage to `model`
- Extracts `Mode` to a standalone file as `QuizMode`

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/quiz/QuizAnswerCommand.java [hunk 1]
```diff
@@ -8,21 +8,21 @@
...
 public class QuizAnswerCommand implements Command {
     public static final String COMMAND_WORD = "answer";
     public static final String MESSAGE_USAGE = COMMAND_WORD + ": * any character except word that starts with \\\n";
-    public static final String MESSAGE_QUESTION = "Question: %1$s\n";
-    public static final String MESSAGE_QUESTION_ANSWER = "Question: %1$s\nAnswer: %2$s";
     public static final String MESSAGE_CORRECT = "Your answer is correct.\n";
-    public static final String MESSAGE_WRONG_ONCE = "Your answer is wrong, you have one more chance to answer it\n";
-    public static final String MESSAGE_WRONG = "The correct answer is %1$s.\n";
+    public static final String MESSAGE_WRONG_ONCE = "Your answer %1$s is wrong, "
+        + "you have one more chance to answer it\n";
```
Comment (DigiPie) [inline src/main/java/seedu/address/logic/commands/quiz/QuizAnswerCommand.java]: Your `MESSAGE_WRONG_ONCE` is missing a full stop at the end of the sentence.

File: src/main/java/seedu/address/logic/LogicManager.java [hunk 2]
```diff
@@ -47,15 +48,14 @@ public CommandResult execute(String commandText) throws CommandException, ParseE
         CommandResult commandResult;
         try {
             Command command = null;
-            if (quizModel.isQuizDone()) {
+            if (getMode().equals("management")) {
```
Comment (DigiPie) [inline src/main/java/seedu/address/logic/LogicManager.java]: Consider replacing this with an `enum` just like you did for your `Quiz.Mode`.

For example:

```java
enum Mode
{ 
    MANAGEMENT, QUIZ;
} 
```

Then change the `if...else` block here to:

```java
switch(getMode()) {
  case MANAGEMENT:
    command = managementModeParser.parse(commandText);
    commandResult = command.execute(managementModel, history);
    break;
  case QUIZ:
  default:
    command = quizModeParser.parse(commandText);
    commandResult = command.execute(quizModel, history);
}
```

File: src/main/java/seedu/address/logic/commands/quiz/QuizDifficultCommand.java [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+import seedu.address.model.modelmanager.QuizModel;
+import seedu.address.model.quiz.QuizCard;
+
+/**
+ * Label a card as difficult or not
+ */
+public class QuizDifficultCommand implements Command {
+    public static final String COMMAND_WORD = "\\difficult";
+    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Label this current question as difficult\n";
+    public static final String MESSAGE_SUCCESS = "Current question is labelled as %1$s.";
```
Comment (DigiPie) [inline src/main/java/seedu/address/logic/commands/quiz/QuizDifficultCommand.java]: World Choice: Using "This question..." instead of "Current question..." may be even clearer to the user. Just a suggestion.

File: src/main/java/seedu/address/logic/commands/quiz/QuizStartCommand.java [hunk 4]
```diff
@@ -65,8 +62,15 @@ public CommandResult executeActual(QuizModel model, CommandHistory history) {
         model.init(quiz);
         QuizCard card = model.getNextCard();
 
-        return new CommandResult(String.format(MESSAGE_QUESTION_ANSWER, card.getQuestion(), card.getAnswer()),
-            true, false, false);
+        if (card.getQuizMode() == Quiz.Mode.PREVIEW) {
```
Comment (DigiPie) [inline src/main/java/seedu/address/logic/commands/quiz/QuizStartCommand.java]: Good usage of `enum`. But you should consider changing this to a switch conditional statement so it will be clearer to other programmers an `enum` is being used.

**Comment by halcyoneee** [comment]
> Good job @halcyoneee . Your code is generally quite understandable even without comments, and the comments provided were helpful too. Do take a look at my suggestions and let me know if you have any queries.

Thanks for the review, however, I think that for short if-else it doesn't affect the readability as compared to switch statement so I have retained the current code.

**Comment by DigiPie** [comment]
> 
> 
> > Good job @halcyoneee . Your code is generally quite understandable even without comments, and the comments provided were helpful too. Do take a look at my suggestions and let me know if you have any queries.
> 
> Thanks for the review, however, I think that for short if-else it doesn't affect the readability as compared to switch statement so I have retained the current code.

Alright noted. Your code looks good-to-go. I will merge it into `v1.3` now.
